moved the client install section to be after the DNS setup
git-svn-id: https://svn.devel.redhat.com/repos/ipa-tests/trunk@230 aeb79ed8-e03d-0410-be94-af332b95afa2

diff --git a/ipa-tests/tet/Shared/Full_Install b/ipa-tests/tet/Shared/Full_Install
--- a/ipa-tests/tet/Shared/Full_Install
+++ b/ipa-tests/tet/Shared/Full_Install
@@ -135,19 +135,6 @@ tp4()
 			if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
 		fi
 	done
-	for s in $CLIENTS; do
-		if [ "$s" != "" ]; then
-			echo "working on $s now"
-			if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
-			SetupClient $s
-			ret=$?
-			if [ $ret -ne 0 ]; then
-				echo "client-install of server on $s ssh failed"
-				return 1
-			fi
-		fi
-		if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
-	done
 
 			ssh root@$FULLHOSTNAME "ps -ef | grep slapd"
 	return 0
@@ -196,6 +183,34 @@ tp5()
 
 }
 ######################################################################
+
+######################################################################
+# Setup the clients
+######################################################################
+tp6()
+{
+	set -x
+	echo "START tp6"
+
+	for s in $CLIENTS; do
+		if [ "$s" != "" ]; then
+			echo "working on $s now"
+			if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
+			eval_vars $s
+			ssh root@$FULLHOSTNAME "/etc/init.d/ntpd stop; ntpdate $NTPSERVER"
+			SetupClient $s
+			ret=$?
+			if [ $ret -ne 0 ]; then
+				echo "client-install of server on $s ssh failed"
+				return 1
+			fi
+		fi
+		if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
+	done
+
+			ssh root@$FULLHOSTNAME "ps -ef | grep slapd"
+	return 0
+}
 
 instclean()
 {
@@ -280,6 +295,12 @@ RunFullInstall()
 	ret=$?
 	if [ $ret -ne 0 ]; then
 		echo "tp5 failed"
+		return 1
+	fi
+	tp6
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "tp6 failed"
 		return 1
 	fi
 
