added changes for working install/uninstall shared libs
git-svn-id: https://svn.devel.redhat.com/repos/ipa-tests/trunk@89 aeb79ed8-e03d-0410-be94-af332b95afa2

diff --git a/ipa-tests/tet/Shared/Full_Install b/ipa-tests/tet/Shared/Full_Install
--- a/ipa-tests/tet/Shared/Full_Install
+++ b/ipa-tests/tet/Shared/Full_Install
@@ -1,4 +1,7 @@
 #!/bin/ksh
+# This file is called by engage to install the rpms and packages 
+# to all of the servers and clients.
+# Any additions here should also be made to the quickinstall acceptance test
 
 setupssh()
 {
@@ -101,43 +104,6 @@ tp2()
 ######################################################################
 
 ######################################################################
-# This is a negitive test case. The test itself will succeeed, but the 
-# underlying test runs a bad ipa-server-install that should fail
-######################################################################
-tp3()
-{
-	echo "START tp3"
-	for s in $SERVERS; do
-		if [ "$s" != "" ]; then
-			if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
-			SetupServerBogus $s
-			ret=$?
-			if [ $ret -ne 0 ]; then
-				echo "server-install of server on $s ssh failed"
-				return 1
-			fi
-			if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
-		fi
-	done
-	for s in $CLIENTS; do
-		if [ "$s" != "" ]; then
-			if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
-			SetupClientBogus $s
-			ret=$?
-			if [ $ret -ne 0 ]; then
-				echo "client-install of server on $s ssh failed"
-				return 1
-			fi
-			if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
-		fi
-	done
-
-	return 0
-
-}
-######################################################################
-
-######################################################################
 tp4()
 {
 	echo "START tp4"
@@ -170,6 +136,33 @@ tp4()
 				echo "client-install of server on $s ssh failed"
 				return 1
 			fi
+		fi
+		if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
+	done
+
+	return 0
+
+}
+######################################################################
+
+######################################################################
+# Run some DNS test to make sure everything is working, if so, set 
+# resolv.conf to point to the right place.
+######################################################################
+tp5()
+{
+	set -x
+	echo "START tp5"
+	# Get the IP of the first server to be used in the DNS tests.
+	eval_vars M1
+	export dnss=$IP
+	for s in "$SERVERS $CLIENTS"; do
+		if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
+		FixResolv $s
+		ret=$?
+		if [ $ret != 0 ]; then
+			echo "ERROR - repair of resolv.conf on $s failed";
+			return 1
 		fi
 		if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
 	done
@@ -221,13 +214,51 @@ RunFullInstall()
 
 	# The next line is required as it picks up data about the servers to use
 	CheckAlive
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "Some servers or clients not alive"
+		return 1
+	fi
 	setupssh
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "Setup of ssh on one or more of the servers or clients failed"
+		return 1
+	fi
 	tp1
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "tp1 failed"
+		return 1
+	fi
 	tp2
-	tp3
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "tp2 failed"
+		return 1
+	fi
+#	tp3
+#	ret=$?
+#	if [ $ret -ne 0 ]; then
+#		echo "tp3 failed"
+#		return 1
+#	fi
 	tp4
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "tp4 failed"
+		return 1
+	fi
+	tp5
+	ret=$?
+	if [ $ret -ne 0 ]; then
+		echo "tp5 failed"
+		return 1
+	fi
+
 	instclean
 
+	return 0
 }
 
 . $TESTING_SHARED/instlib.ksh
@@ -236,4 +267,4 @@ RunFullInstall()
 if [ "$DSTET_DEBUG" = "y" ]; then set -x; fi
 RunFullInstall
 
-#. $TET_ROOT/lib/ksh/tcm.ksh
+
