install now handles modification of the dns zone, uninstall does not leave resolv.conf broken any more
git-svn-id: https://svn.devel.redhat.com/repos/ipa-tests/trunk@90 aeb79ed8-e03d-0410-be94-af332b95afa2

diff --git a/ipa-tests/tet/Shared/Full_Install b/ipa-tests/tet/Shared/Full_Install
--- a/ipa-tests/tet/Shared/Full_Install
+++ b/ipa-tests/tet/Shared/Full_Install
@@ -156,7 +156,7 @@ tp5()
 	# Get the IP of the first server to be used in the DNS tests.
 	eval_vars M1
 	export dnss=$IP
-	for s in "$SERVERS $CLIENTS"; do
+	for s in $SERVERS; do
 		if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
 		FixResolv $s
 		ret=$?
@@ -164,9 +164,19 @@ tp5()
 			echo "ERROR - repair of resolv.conf on $s failed";
 			return 1
 		fi
-		if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
 	done
 
+	for s in $CLIENTS; do
+		if [ "$DSTET_DEBUG" = "y" ]; then echo "working on $s now"; fi
+		FixResolv $s
+		ret=$?
+		if [ $ret != 0 ]; then
+			echo "ERROR - repair of resolv.conf on $s failed";
+			return 1
+		fi
+	done
+
+	if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
 	return 0
 
 }
