added changes to make all servers not the first one replicas. Also added some recursion to make the yum installs more stable
git-svn-id: https://svn.devel.redhat.com/repos/ipa-tests/trunk@91 aeb79ed8-e03d-0410-be94-af332b95afa2

diff --git a/ipa-tests/tet/Shared/Full_Install b/ipa-tests/tet/Shared/Full_Install
--- a/ipa-tests/tet/Shared/Full_Install
+++ b/ipa-tests/tet/Shared/Full_Install
@@ -117,11 +117,13 @@ tp4()
 				echo "server-install of server on $s ssh failed"
 				return 1
 			fi
-			FixBindServer $s
-			ret=$?
-			if [ $ret -ne 0 ]; then
-				echo "fix-bind-server on $s ssh failed"
-				return 1
+			if [ "$s" == "M1" ]; then
+				FixBindServer $s
+				ret=$?
+				if [ $ret -ne 0 ]; then
+					echo "fix-bind-server on $s ssh failed"
+					return 1
+				fi
 			fi
 			if [ "$DSTET_DEBUG" = "y" ]; then echo "done working on $s"; fi
 		fi
